<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();
        $countries = array(
            array('id' => 1, 'name' => "Afghanistan", 'phone_code' => 93),
            array('id' => 2, 'name' => "Albania", 'phone_code' => 355),
            array('id' => 3, 'name' => "Algeria", 'phone_code' => 213),
            array('id' => 4, 'name' => "American Samoa", 'phone_code' => 1684),
            array('id' => 5, 'name' => "Andorra", 'phone_code' => 376),
            array('id' => 6, 'name' => "Angola", 'phone_code' => 244),
            array('id' => 7, 'name' => "Anguilla", 'phone_code' => 1264),
            array('id' => 8, 'name' => "Antarctica", 'phone_code' => 0),
            array('id' => 9, 'name' => "Antigua And Barbuda", 'phone_code' => 1268),
            array('id' => 10, 'name' => "Argentina", 'phone_code' => 54),
            array('id' => 11, 'name' => "Armenia", 'phone_code' => 374),
            array('id' => 12, 'name' => "Aruba", 'phone_code' => 297),
            array('id' => 13, 'name' => "Australia", 'phone_code' => 61),
            array('id' => 14, 'name' => "Austria", 'phone_code' => 43),
            array('id' => 15, 'name' => "Azerbaijan", 'phone_code' => 994),
            array('id' => 16, 'name' => "Bahamas The", 'phone_code' => 1242),
            array('id' => 17, 'name' => "Bahrain", 'phone_code' => 973),
            array('id' => 18, 'name' => "Bangladesh", 'phone_code' => 880),
            array('id' => 19, 'name' => "Barbados", 'phone_code' => 1246),
            array('id' => 20, 'name' => "Belarus", 'phone_code' => 375),
            array('id' => 21, 'name' => "Belgium", 'phone_code' => 32),
            array('id' => 22, 'name' => "Belize", 'phone_code' => 501),
            array('id' => 23, 'name' => "Benin", 'phone_code' => 229),
            array('id' => 24, 'name' => "Bermuda", 'phone_code' => 1441),
            array('id' => 25, 'name' => "Bhutan", 'phone_code' => 975),
            array('id' => 26, 'name' => "Bolivia", 'phone_code' => 591),
            array('id' => 27, 'name' => "Bosnia and Herzegovina", 'phone_code' => 387),
            array('id' => 28, 'name' => "Botswana", 'phone_code' => 267),
            array('id' => 29, 'name' => "Bouvet Island", 'phone_code' => 0),
            array('id' => 30, 'name' => "Brazil", 'phone_code' => 55),
            array('id' => 31, 'name' => "British Indian Ocean Territory", 'phone_code' => 246),
            array('id' => 32, 'name' => "Brunei", 'phone_code' => 673),
            array('id' => 33, 'name' => "Bulgaria", 'phone_code' => 359),
            array('id' => 34, 'name' => "Burkina Faso", 'phone_code' => 226),
            array('id' => 35, 'name' => "Burundi", 'phone_code' => 257),
            array('id' => 36, 'name' => "Cambodia", 'phone_code' => 855),
            array('id' => 37, 'name' => "Cameroon", 'phone_code' => 237),
            array('id' => 38, 'name' => "Canada", 'phone_code' => 1),
            array('id' => 39, 'name' => "Cape Verde", 'phone_code' => 238),
            array('id' => 40, 'name' => "Cayman Islands", 'phone_code' => 1345),
            array('id' => 41, 'name' => "Central African Republic", 'phone_code' => 236),
            array('id' => 42, 'name' => "Chad", 'phone_code' => 235),
            array('id' => 43, 'name' => "Chile", 'phone_code' => 56),
            array('id' => 44, 'name' => "China", 'phone_code' => 86),
            array('id' => 45, 'name' => "Christmas Island", 'phone_code' => 61),
            array('id' => 46, 'name' => "Cocos (Keeling) Islands", 'phone_code' => 672),
            array('id' => 47, 'name' => "Colombia", 'phone_code' => 57),
            array('id' => 48, 'name' => "Comoros", 'phone_code' => 269),
            array('id' => 49, 'name' => "Congo", 'phone_code' => 242),
            array('id' => 50, 'name' => "Congo The Democratic Republic Of The", 'phone_code' => 242),
            array('id' => 51, 'name' => "Cook Islands", 'phone_code' => 682),
            array('id' => 52, 'name' => "Costa Rica", 'phone_code' => 506),
            array('id' => 53, 'name' => "Cote D Ivoire (Ivory Coast)", 'phone_code' => 225),
            array('id' => 54, 'name' => "Croatia (Hrvatska)", 'phone_code' => 385),
            array('id' => 55, 'name' => "Cuba", 'phone_code' => 53),
            array('id' => 56, 'name' => "Cyprus", 'phone_code' => 357),
            array('id' => 57, 'name' => "Czech Republic", 'phone_code' => 420),
            array('id' => 58, 'name' => "Denmark", 'phone_code' => 45),
            array('id' => 59, 'name' => "Djibouti", 'phone_code' => 253),
            array('id' => 60, 'name' => "Dominica", 'phone_code' => 1767),
            array('id' => 61, 'name' => "Dominican Republic", 'phone_code' => 1809),
            array('id' => 62, 'name' => "East Timor", 'phone_code' => 670),
            array('id' => 63, 'name' => "Ecuador", 'phone_code' => 593),
            array('id' => 64, 'name' => "Egypt", 'phone_code' => 20),
            array('id' => 65, 'name' => "El Salvador", 'phone_code' => 503),
            array('id' => 66, 'name' => "Equatorial Guinea", 'phone_code' => 240),
            array('id' => 67, 'name' => "Eritrea", 'phone_code' => 291),
            array('id' => 68, 'name' => "Estonia", 'phone_code' => 372),
            array('id' => 69, 'name' => "Ethiopia", 'phone_code' => 251),
            array('id' => 70, 'name' => "External Territories of Australia", 'phone_code' => 61),
            array('id' => 71, 'name' => "Falkland Islands", 'phone_code' => 500),
            array('id' => 72, 'name' => "Faroe Islands", 'phone_code' => 298),
            array('id' => 73, 'name' => "Fiji Islands", 'phone_code' => 679),
            array('id' => 74, 'name' => "Finland", 'phone_code' => 358),
            array('id' => 75, 'name' => "France", 'phone_code' => 33),
            array('id' => 76, 'name' => "French Guiana", 'phone_code' => 594),
            array('id' => 77, 'name' => "French Polynesia", 'phone_code' => 689),
            array('id' => 78, 'name' => "French Southern Territories", 'phone_code' => 0),
            array('id' => 79, 'name' => "Gabon", 'phone_code' => 241),
            array('id' => 80, 'name' => "Gambia The", 'phone_code' => 220),
            array('id' => 81, 'name' => "Georgia", 'phone_code' => 995),
            array('id' => 82, 'name' => "Germany", 'phone_code' => 49),
            array('id' => 83, 'name' => "Ghana", 'phone_code' => 233),
            array('id' => 84, 'name' => "Gibraltar", 'phone_code' => 350),
            array('id' => 85, 'name' => "Greece", 'phone_code' => 30),
            array('id' => 86, 'name' => "Greenland", 'phone_code' => 299),
            array('id' => 87, 'name' => "Grenada", 'phone_code' => 1473),
            array('id' => 88, 'name' => "Guadeloupe", 'phone_code' => 590),
            array('id' => 89, 'name' => "Guam", 'phone_code' => 1671),
            array('id' => 90, 'name' => "Guatemala", 'phone_code' => 502),
            array('id' => 91, 'name' => "Guernsey and Alderney", 'phone_code' => 44),
            array('id' => 92, 'name' => "Guinea", 'phone_code' => 224),
            array('id' => 93, 'name' => "Guinea-Bissau", 'phone_code' => 245),
            array('id' => 94, 'name' => "Guyana", 'phone_code' => 592),
            array('id' => 95, 'name' => "Haiti", 'phone_code' => 509),
            array('id' => 96, 'name' => "Heard and McDonald Islands", 'phone_code' => 0),
            array('id' => 97, 'name' => "Honduras", 'phone_code' => 504),
            array('id' => 98, 'name' => "Hong Kong S.A.R.", 'phone_code' => 852),
            array('id' => 99, 'name' => "Hungary", 'phone_code' => 36),
            array('id' => 100, 'name' => "Iceland", 'phone_code' => 354),
            array('id' => 101, 'name' => "India", 'phone_code' => 91),
            array('id' => 102, 'name' => "Indonesia", 'phone_code' => 62),
            array('id' => 103, 'name' => "Iran", 'phone_code' => 98),
            array('id' => 104, 'name' => "Iraq", 'phone_code' => 964),
            array('id' => 105, 'name' => "Ireland", 'phone_code' => 353),
            array('id' => 106, 'name' => "Israel", 'phone_code' => 972),
            array('id' => 107, 'name' => "Italy", 'phone_code' => 39),
            array('id' => 108, 'name' => "Jamaica", 'phone_code' => 1876),
            array('id' => 109, 'name' => "Japan", 'phone_code' => 81),
            array('id' => 110, 'name' => "Jersey", 'phone_code' => 44),
            array('id' => 111, 'name' => "Jordan", 'phone_code' => 962),
            array('id' => 112, 'name' => "Kazakhstan", 'phone_code' => 7),
            array('id' => 113, 'name' => "Kenya", 'phone_code' => 254),
            array('id' => 114, 'name' => "Kiribati", 'phone_code' => 686),
            array('id' => 115, 'name' => "Korea North", 'phone_code' => 850),
            array('id' => 116, 'name' => "Korea South", 'phone_code' => 82),
            array('id' => 117, 'name' => "Kuwait", 'phone_code' => 965),
            array('id' => 118, 'name' => "Kyrgyzstan", 'phone_code' => 996),
            array('id' => 119, 'name' => "Laos", 'phone_code' => 856),
            array('id' => 120, 'name' => "Latvia", 'phone_code' => 371),
            array('id' => 121, 'name' => "Lebanon", 'phone_code' => 961),
            array('id' => 122, 'name' => "Lesotho", 'phone_code' => 266),
            array('id' => 123, 'name' => "Liberia", 'phone_code' => 231),
            array('id' => 124, 'name' => "Libya", 'phone_code' => 218),
            array('id' => 125, 'name' => "Liechtenstein", 'phone_code' => 423),
            array('id' => 126, 'name' => "Lithuania", 'phone_code' => 370),
            array('id' => 127, 'name' => "Luxembourg", 'phone_code' => 352),
            array('id' => 128, 'name' => "Macau S.A.R.", 'phone_code' => 853),
            array('id' => 129, 'name' => "Macedonia", 'phone_code' => 389),
            array('id' => 130, 'name' => "Madagascar", 'phone_code' => 261),
            array('id' => 131, 'name' => "Malawi", 'phone_code' => 265),
            array('id' => 132, 'name' => "Malaysia", 'phone_code' => 60),
            array('id' => 133, 'name' => "Maldives", 'phone_code' => 960),
            array('id' => 134, 'name' => "Mali", 'phone_code' => 223),
            array('id' => 135, 'name' => "Malta", 'phone_code' => 356),
            array('id' => 136, 'name' => "Man (Isle of)", 'phone_code' => 44),
            array('id' => 137, 'name' => "Marshall Islands", 'phone_code' => 692),
            array('id' => 138, 'name' => "Martinique", 'phone_code' => 596),
            array('id' => 139, 'name' => "Mauritania", 'phone_code' => 222),
            array('id' => 140, 'name' => "Mauritius", 'phone_code' => 230),
            array('id' => 141, 'name' => "Mayotte", 'phone_code' => 269),
            array('id' => 142, 'name' => "Mexico", 'phone_code' => 52),
            array('id' => 143, 'name' => "Micronesia", 'phone_code' => 691),
            array('id' => 144, 'name' => "Moldova", 'phone_code' => 373),
            array('id' => 145, 'name' => "Monaco", 'phone_code' => 377),
            array('id' => 146, 'name' => "Mongolia", 'phone_code' => 976),
            array('id' => 147, 'name' => "Montserrat", 'phone_code' => 1664),
            array('id' => 148, 'name' => "Morocco", 'phone_code' => 212),
            array('id' => 149, 'name' => "Mozambique", 'phone_code' => 258),
            array('id' => 150, 'name' => "Myanmar", 'phone_code' => 95),
            array('id' => 151, 'name' => "Namibia", 'phone_code' => 264),
            array('id' => 152, 'name' => "Nauru", 'phone_code' => 674),
            array('id' => 153, 'name' => "Nepal", 'phone_code' => 977),
            array('id' => 154, 'name' => "Netherlands Antilles", 'phone_code' => 599),
            array('id' => 155, 'name' => "Netherlands The", 'phone_code' => 31),
            array('id' => 156, 'name' => "New Caledonia", 'phone_code' => 687),
            array('id' => 157, 'name' => "New Zealand", 'phone_code' => 64),
            array('id' => 158, 'name' => "Nicaragua", 'phone_code' => 505),
            array('id' => 159, 'name' => "Niger", 'phone_code' => 227),
            array('id' => 160, 'name' => "Nigeria", 'phone_code' => 234),
            array('id' => 161, 'name' => "Niue", 'phone_code' => 683),
            array('id' => 162, 'name' => "Norfolk Island", 'phone_code' => 672),
            array('id' => 163, 'name' => "Northern Mariana Islands", 'phone_code' => 1670),
            array('id' => 164, 'name' => "Norway", 'phone_code' => 47),
            array('id' => 165, 'name' => "Oman", 'phone_code' => 968),
            array('id' => 166, 'name' => "Pakistan", 'phone_code' => 92),
            array('id' => 167, 'name' => "Palau", 'phone_code' => 680),
            array('id' => 168, 'name' => "Palestinian Territory Occupied", 'phone_code' => 970),
            array('id' => 169, 'name' => "Panama", 'phone_code' => 507),
            array('id' => 170, 'name' => "Papua new Guinea", 'phone_code' => 675),
            array('id' => 171, 'name' => "Paraguay", 'phone_code' => 595),
            array('id' => 172, 'name' => "Peru", 'phone_code' => 51),
            array('id' => 173, 'name' => "Philippines", 'phone_code' => 63),
            array('id' => 174, 'name' => "Pitcairn Island", 'phone_code' => 0),
            array('id' => 175, 'name' => "Poland", 'phone_code' => 48),
            array('id' => 176, 'name' => "Portugal", 'phone_code' => 351),
            array('id' => 177, 'name' => "Puerto Rico", 'phone_code' => 1787),
            array('id' => 178, 'name' => "Qatar", 'phone_code' => 974),
            array('id' => 179, 'name' => "Reunion", 'phone_code' => 262),
            array('id' => 180, 'name' => "Romania", 'phone_code' => 40),
            array('id' => 181, 'name' => "Russia", 'phone_code' => 70),
            array('id' => 182, 'name' => "Rwanda", 'phone_code' => 250),
            array('id' => 183, 'name' => "Saint Helena", 'phone_code' => 290),
            array('id' => 184, 'name' => "Saint Kitts And Nevis", 'phone_code' => 1869),
            array('id' => 185, 'name' => "Saint Lucia", 'phone_code' => 1758),
            array('id' => 186, 'name' => "Saint Pierre and Miquelon", 'phone_code' => 508),
            array('id' => 187, 'name' => "Saint Vincent And The Grenadines", 'phone_code' => 1784),
            array('id' => 188, 'name' => "Samoa", 'phone_code' => 684),
            array('id' => 189, 'name' => "San Marino", 'phone_code' => 378),
            array('id' => 190, 'name' => "Sao Tome and Principe", 'phone_code' => 239),
            array('id' => 191, 'name' => "Saudi Arabia", 'phone_code' => 966),
            array('id' => 192, 'name' => "Senegal", 'phone_code' => 221),
            array('id' => 193, 'name' => "Serbia", 'phone_code' => 381),
            array('id' => 194, 'name' => "Seychelles", 'phone_code' => 248),
            array('id' => 195, 'name' => "Sierra Leone", 'phone_code' => 232),
            array('id' => 196, 'name' => "Singapore", 'phone_code' => 65),
            array('id' => 197, 'name' => "Slovakia", 'phone_code' => 421),
            array('id' => 198, 'name' => "Slovenia", 'phone_code' => 386),
            array('id' => 199, 'name' => "Smaller Territories of the UK", 'phone_code' => 44),
            array('id' => 200, 'name' => "Solomon Islands", 'phone_code' => 677),
            array('id' => 201, 'name' => "Somalia", 'phone_code' => 252),
            array('id' => 202, 'name' => "South Africa", 'phone_code' => 27),
            array('id' => 203, 'name' => "South Georgia", 'phone_code' => 0),
            array('id' => 204, 'name' => "South Sudan", 'phone_code' => 211),
            array('id' => 205, 'name' => "Spain", 'phone_code' => 34),
            array('id' => 206, 'name' => "Sri Lanka", 'phone_code' => 94),
            array('id' => 207, 'name' => "Sudan", 'phone_code' => 249),
            array('id' => 208, 'name' => "Suriname", 'phone_code' => 597),
            array('id' => 209, 'name' => "Svalbard And Jan Mayen Islands", 'phone_code' => 47),
            array('id' => 210, 'name' => "Swaziland", 'phone_code' => 268),
            array('id' => 211, 'name' => "Sweden", 'phone_code' => 46),
            array('id' => 212, 'name' => "Switzerland", 'phone_code' => 41),
            array('id' => 213, 'name' => "Syria", 'phone_code' => 963),
            array('id' => 214, 'name' => "Taiwan", 'phone_code' => 886),
            array('id' => 215, 'name' => "Tajikistan", 'phone_code' => 992),
            array('id' => 216, 'name' => "Tanzania", 'phone_code' => 255),
            array('id' => 217, 'name' => "Thailand", 'phone_code' => 66),
            array('id' => 218, 'name' => "Togo", 'phone_code' => 228),
            array('id' => 219, 'name' => "Tokelau", 'phone_code' => 690),
            array('id' => 220, 'name' => "Tonga", 'phone_code' => 676),
            array('id' => 221, 'name' => "Trinidad And Tobago", 'phone_code' => 1868),
            array('id' => 222, 'name' => "Tunisia", 'phone_code' => 216),
            array('id' => 223, 'name' => "Turkey", 'phone_code' => 90),
            array('id' => 224, 'name' => "Turkmenistan", 'phone_code' => 7370),
            array('id' => 225, 'name' => "Turks And Caicos Islands", 'phone_code' => 1649),
            array('id' => 226, 'name' => "Tuvalu", 'phone_code' => 688),
            array('id' => 227, 'name' => "Uganda", 'phone_code' => 256),
            array('id' => 228, 'name' => "Ukraine", 'phone_code' => 380),
            array('id' => 229, 'name' => "United Arab Emirates", 'phone_code' => 971),
            array('id' => 230, 'name' => "United Kingdom", 'phone_code' => 44),
            array('id' => 231, 'name' => "United States", 'phone_code' => 1),
            array('id' => 232, 'name' => "United States Minor Outlying Islands", 'phone_code' => 1),
            array('id' => 233, 'name' => "Uruguay", 'phone_code' => 598),
            array('id' => 234, 'name' => "Uzbekistan", 'phone_code' => 998),
            array('id' => 235, 'name' => "Vanuatu", 'phone_code' => 678),
            array('id' => 236, 'name' => "Vatican City State (Holy See)", 'phone_code' => 39),
            array('id' => 237, 'name' => "Venezuela", 'phone_code' => 58),
            array('id' => 238, 'name' => "Vietnam", 'phone_code' => 84),
            array('id' => 239, 'name' => "Virgin Islands (British)", 'phone_code' => 1284),
            array('id' => 240, 'name' => "Virgin Islands (US)", 'phone_code' => 1340),
            array('id' => 241, 'name' => "Wallis And Futuna Islands", 'phone_code' => 681),
            array('id' => 242, 'name' => "Western Sahara", 'phone_code' => 212),
            array('id' => 243, 'name' => "Yemen", 'phone_code' => 967),
            array('id' => 244, 'name' => "Yugoslavia", 'phone_code' => 38),
            array('id' => 245, 'name' => "Zambia", 'phone_code' => 260),
            array('id' => 246, 'name' => "Zimbabwe", 'phone_code' => 263),
        );
        \DB::table('countries')->insert($countries);
        // foreach ($countries as $item) {
        //     Country::create($item);
        // }
    }
}
